default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5 ) %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'graphql_test_backend_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'graphql_test_backend_test') %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
